name: Feature Branch CI/CD

on:
  push:
    branches:
      - 'feature/*'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Python Code 
        run: python -V

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Typescript Code 
        run: npm --version 
 
  pytest:
    needs: flake8 
    runs-on: ubuntu-latest
    steps:
      - name: Test Python Code 
        run: echo "PYTHON UNIT TESTING COMPLETE"
 
  jest:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Test Typescript Code 
        run: echo "TYPESCRIPT UNIT TESTING COMPLETE"

