name: Feature Branch CI/CD

on:
  push:
    branches:
      - 'feature/*'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Python Code 
        run: python -V

  eslint:
    runs-on: ubuntu-latest
    steps:
 
      - name: Checkout
        uses: actions/checkout@v2

      - id: file_changes
        name: Get Changed Files
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','
          fileOutput: ','

      - name: Output Changed Files 
        run: |
          echo "Changed Files (~/files.csv):"
          cat $HOME/files.csv

      - name: Lint
        run: |
          yarn --version
          yarn workspaces foreach run lint 


  pytest:
    needs: flake8 
    runs-on: ubuntu-latest
    steps:
      - name: Test Python Code 
        run: echo "PYTHON UNIT TESTING COMPLETE"
 
  jest:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Test Typescript Code 
        run: echo "TYPESCRIPT UNIT TESTING COMPLETE"

